// <auto-generated />
using System;
using Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.AutorEntity", b =>
                {
                    b.Property<int>("autor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("autor_id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("nacionalidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("autor_id");

                    b.ToTable("Autores", (string)null);
                });

            modelBuilder.Entity("Domain.LibroEntity", b =>
                {
                    b.Property<int>("libro_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("libro_id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ano_publicacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("autor_id")
                        .HasColumnType("int");

                    b.Property<string>("genero")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("libro_id");

                    b.HasIndex("ano_publicacion");

                    b.HasIndex("autor_id");

                    b.HasIndex("genero");

                    b.ToTable("Libros", (string)null);
                });

            modelBuilder.Entity("Domain.PrestamoEntity", b =>
                {
                    b.Property<int>("prestamo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("prestamo_id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_devolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_prestamo")
                        .HasColumnType("datetime2");

                    b.Property<int>("libro_id")
                        .HasColumnType("int");

                    b.HasKey("prestamo_id");

                    b.HasIndex("fecha_devolucion");

                    b.HasIndex("fecha_prestamo");

                    b.HasIndex("libro_id");

                    b.ToTable("Prestamos", (string)null);
                });

            modelBuilder.Entity("Domain.LibroEntity", b =>
                {
                    b.HasOne("Domain.AutorEntity", "autor")
                        .WithMany()
                        .HasForeignKey("autor_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("autor");
                });

            modelBuilder.Entity("Domain.PrestamoEntity", b =>
                {
                    b.HasOne("Domain.LibroEntity", "libro")
                        .WithMany()
                        .HasForeignKey("libro_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("libro");
                });
#pragma warning restore 612, 618
        }
    }
}
